version: '3.9'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/code
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
  db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=fastapi_traefik
        - POSTGRES_PASSWORD=fastapi_traefik
        - POSTGRES_DB=fastapi_traefik
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data: